name: Sauvegarde du Trafic GitHub

on:
  schedule:
    - cron: '0 0 * * *' # S'exécute tous les jours à minuit
  workflow_dispatch: # Permet de lancer le script manuellement depuis l'interface

jobs:
  backup_traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Nécessaire pour que l'Action puisse écrire dans le dépôt

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Récupération des vues via l'API native
        run: |
          curl -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/traffic/views > traffic_views.json

      - name: Sauvegarde et Push dans le dépôt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add traffic_views.json
          git commit -m "Mise à jour automatique des statistiques de trafic" || echo "Rien à mettre à jour"
          git push
